# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: flutter build app
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            platform: linux
            binary-name: papers_linux_amd64
          - runs-on: macos-latest
            platform: macos
            binary-name: papers_macos_amd64
          - runs-on: windows-latest
            platform: windows
            binary-name: papers_windows.exe
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - run: mkdir ${{ matrix.runs-on }}
      - name: Build app
        run: flutter build ${{ matrix.platform }} ${{ matrix.runs-on }}/${{ matrix.binary-name }}
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: bin-${{ matrix.runs-on }}
          path: ${{ matrix.runs-on }}

  release:
    needs: build
    name: github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3.0.0
        with:
          name: bin-ubuntu-latest
          path: bin-linux
      - uses: actions/download-artifact@v3.0.1
        with:
          name: bin-macos-latest
          path: bin-macos
      - uses: actions/download-artifact@v3.0.1
        with:
          name: bin-windows-latest
          path: bin-windows
      - uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          files: bin-*/*
